In [ ]:
import torch

In [ ]:
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
[1,2,5,6], [1,6,6,6], [1,7,7,7] ])

y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0],
[1,0,0], [1,0,0] ])

print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8, 3])


In [ ]:
W = torch.zeros(4,3, requires_grad=True)
b = torch.zeros(1,3, requires_grad=True)

print(W.size())
print(b.size())

torch.Size([4, 3])
torch.Size([1, 3])


In [ ]:
optimizer = torch.optim.Adam([W,b], lr=0.1)

In [ ]:
for epoch in range(3001):
  hypothesis = torch.softmax(torch.mm(x_train, W)+b, dim=1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))
    #print(f"epoch:{epoch}, cost:{cost.item():.6f}")

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105263
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [ ]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)

print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 5.5163e-19, 7.0150e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])




> 개선사항



In [60]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [61]:
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
[1,2,5,6], [1,6,6,6], [1,7,7,7] ])

y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

print(x_train.size())
print(y_train.size())

torch.Size([8, 4])
torch.Size([8])


In [62]:
W = torch.zeros(4,3, requires_grad=True)
b = torch.zeros(1,3, requires_grad=True)

print(W.size())
print(b.size())

torch.Size([4, 3])
torch.Size([1, 3])


In [63]:
model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(), lr=1)

In [64]:
for epoch in range(3001):
  z = model(x_train)
  cost = F.cross_entropy(z, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))
    #print(f"epoch:{epoch}, cost:{cost.item():.6f}")

epoch: 0, cost: 2.244181
epoch: 300, cost: 0.026132
epoch: 600, cost: 0.009750
epoch: 900, cost: 0.005176
epoch: 1200, cost: 0.003224
epoch: 1500, cost: 0.002197
epoch: 1800, cost: 0.001584
epoch: 2100, cost: 0.001188
epoch: 2400, cost: 0.000916
epoch: 2700, cost: 0.000721
epoch: 3000, cost: 0.000577


In [68]:
x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(model(x_test), dim=1)

print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 1.8597e-25, 0.0000e+00],
        [1.8636e-06, 7.6765e-01, 2.3235e-01],
        [1.1210e-44, 1.1812e-14, 1.0000e+00]], grad_fn=<SoftmaxBackward>)
tensor([0, 1, 2])
