In [ ]:
import numpy as np

In [ ]:
np.random.seed(0)

N, D = 3, 4

x = np.random.randn(N, D)
y = np.random.randn(N, D)
z = np.random.randn(N, D)

In [ ]:
a = x * y
b = a + z
c = np.sum(b)

In [ ]:
grad_c = 1.0
grad_b = grad_c * np.ones((N, D))

# sum 이니까 그래도 전파 fanout
grad_a = grad_b.copy()
grad_z = grad_b.copy()

# 곱이니까 다른 쪽이랑 곱해짐
grad_x = grad_a * y
grad_y = grad_a * x

print("grad_c : ", grad_c)
print("grad_b : ", grad_b)
print("grad_a : ", grad_a)
print("grad_z : ", grad_z)
print("grad_x : ", grad_x)
print("grad_y : ", grad_y)

grad_c :  1.0
grad_b :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
grad_a :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
grad_z :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
grad_x :  [[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]
grad_y :  [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]]


In [13]:
import torch

x = torch.randn(N,D)
x.requires_grad_(True)
y = torch.randn(N,D)
y.requires_grad_(True)
z = torch.randn(N,D)
z.requires_grad_(True)

a = x * y
b = a + z
c = torch.sum(b)

c.backward()
print("x미분 : ", x.grad)
print("y미분 : ", y.grad)

x미분 :  tensor([[ 1.0746,  1.0132, -0.2212,  0.3857],
        [-0.3626, -0.2665,  0.8197,  2.4376],
        [ 1.9834, -1.2383, -1.0736,  0.7226]])
y미분 :  tensor([[ 0.1333,  0.9798,  1.9812, -1.6420],
        [-0.9588, -0.9094,  1.5420, -0.0413],
        [ 0.1907,  1.6129,  1.0234,  0.6547]])
