In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3) # 5 by 3 의 행렬, 초기화 x
print(x)

tensor([[3.7285e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [3]:
x = torch.rand(5,3) #무작위로 초기화된 행렬 생성
print(x)

tensor([[0.0767, 0.2302, 0.2885],
        [0.2689, 0.3884, 0.6887],
        [0.1858, 0.1640, 0.2060],
        [0.5546, 0.8010, 0.3351],
        [0.4714, 0.6534, 0.4849]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [18]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [20]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3514,  0.3643,  0.8800],
        [ 0.6165,  0.1756, -0.8008],
        [-1.5807,  0.1293, -0.8533],
        [-0.7638, -0.1646, -0.8027],
        [-0.4817, -1.5512,  0.1494]])


In [21]:
print(x.size())

torch.Size([5, 3])


In [22]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.3959,  1.2758,  1.1834],
        [ 0.6619,  1.1032, -0.0736],
        [-1.1185,  0.1609, -0.6668],
        [ 0.0075,  0.2541, -0.3132],
        [-0.1313, -1.1696,  1.0584]])


In [24]:
print(torch.add(x, y))

tensor([[ 0.3959,  1.2758,  1.1834],
        [ 0.6619,  1.1032, -0.0736],
        [-1.1185,  0.1609, -0.6668],
        [ 0.0075,  0.2541, -0.3132],
        [-0.1313, -1.1696,  1.0584]])


In [25]:
# 덧셈결과를 인자로 제공
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3959,  1.2758,  1.1834],
        [ 0.6619,  1.1032, -0.0736],
        [-1.1185,  0.1609, -0.6668],
        [ 0.0075,  0.2541, -0.3132],
        [-0.1313, -1.1696,  1.0584]])


In [26]:
y.add_(x)
print(y)
# 바꿔치기 (in-place)방식으로 tensor값을 변경하는 연산뒤에는 _가 붙는다.

tensor([[ 0.3959,  1.2758,  1.1834],
        [ 0.6619,  1.1032, -0.0736],
        [-1.1185,  0.1609, -0.6668],
        [ 0.0075,  0.2541, -0.3132],
        [-0.1313, -1.1696,  1.0584]])


In [28]:
print(x)
print(x[:, 1])

tensor([[ 0.3514,  0.3643,  0.8800],
        [ 0.6165,  0.1756, -0.8008],
        [-1.5807,  0.1293, -0.8533],
        [-0.7638, -0.1646, -0.8027],
        [-0.4817, -1.5512,  0.1494]])
tensor([ 0.3643,  0.1756,  0.1293, -0.1646, -1.5512])


In [31]:
# tensor의 크기변경
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) #-1은 알아서 맞춰줌-> 원래 tensor와 총 크기가 같도록
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
# tensor에 하나의 값만 존재한다면, .item()을 사용하여 값을 얻을 수 있음
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.7071])
-1.7071157693862915


In [33]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [34]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [35]:
a.add_(1)
print(a)
print(b)
# torch tensor와 numpy 배열은 메모리 공간을 공유하기때문에 하나를 변경하면 다른하나도 변경됨

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [37]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x+y
  print(z)
  print(z.to("cpu", torch.double))